### ISSUE TITLE
等价交换mod红物质拳剑设置一击必杀快捷键 按了没用

### ISSUE THREAD

**Issue by mcdreamsource** [canoeStudio/Virtual-Survival---Climate-Control-Remastered#6]

**Comment by Lonelyxiya** [comment]
具体什么问题

**Comment by mcdreamsource** [comment]
标题就是问题（







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "canoeStudio/Virtual-Survival---Climate-Control-Remastered"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月21日(星期六) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [canoeStudio/Virtual-Survival---Climate-Control-Remastered] 等价交换mod红物质拳剑设置一击必杀快捷键 按了没用 (Issue #6)





 
具体什么问题

**Comment by Lonelyxiya** [comment]
pre3 fixed
